# Generated by Django 4.1.1 on 2022-09-24 19:01

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.site')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site_title', models.CharField(max_length=250)),
                ('site_logo', models.ImageField(upload_to=[pathlib.PurePosixPath('/home/max/DEV/UfficioUrbanistica/project/project/static')])),
                ('site_description', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=250)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_official_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Personalizza il sito',
                'verbose_name_plural': 'Personalizza il sito',
            },
            bases=('sites.site', models.Model),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
