# Generated by Django 4.1.1 on 2022-09-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecustomization',
            old_name='address',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='sitecustomization',
            old_name='contact_phone',
            new_name='site_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='contact_official_email',
        ),
    ]
