# Generated by Django 4.1.1 on 2022-09-25 06:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_address_sitecustomization_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecustomization',
            name='contacts',
            field=tinymce.models.HTMLField(),
        ),
    ]
