# Generated by Django 4.1.1 on 2022-09-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitecustomization_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteCustomization',
        ),
    ]
