# Generated by Django 4.1.1 on 2022-09-25 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pathlib
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0004_delete_sitecustomization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site_title', models.CharField(max_length=250)),
                ('site_subtitle', models.CharField(max_length=250)),
                ('site_logo', models.ImageField(upload_to=[pathlib.PurePosixPath('/home/max/DEV/UfficioUrbanistica/project/project/static')])),
                ('site_description', models.CharField(max_length=100)),
                ('contacts', tinymce.models.HTMLField()),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_site', to='sites.site')),
            ],
            options={
                'verbose_name': 'Personalizza il sito',
                'verbose_name_plural': 'Personalizza il sito',
            },
        ),
    ]
