# Generated by Django 4.1.1 on 2022-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecustomization',
            old_name='site_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sitecustomization',
            old_name='site_subtitle',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='sitecustomization',
            old_name='site_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sitecustomization',
            name='site_logo',
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/site'),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='logo',
            field=models.ImageField(default=1, upload_to='uploads/site'),
            preserve_default=False,
        ),
    ]
