# Generated by Django 4.1.1 on 2022-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_site_description_sitecustomization_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecustomization',
            name='header_image',
            field=models.ImageField(default=1, upload_to='uploads/site'),
            preserve_default=False,
        ),
    ]
