version: '3.7'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: db_postgis_staging
    volumes:
      - db-data:/var/lib/postgresql/data
#    networks:
#      - ufficiourbanistica

  website:
    image: maxdragonheart/${PROJECT_NAME}
    build:
      context: ./project
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_PORT: ${PROJECT_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    container_name: ufficiourbanistica_staging
    restart: always
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      - project-static-folder:/app/web/static-folder
      - project-media-folder:/app/web/media-folder
      - project-logs:/app/web/logs
      - project-fixtures:/app/web/project/fixtures
    depends_on:
      - db
#    networks:
#      - ufficiourbanistica

volumes:
  db-data:
  project-static-folder:
  project-media-folder:
  project-logs:
  project-fixtures:

#networks:
#  ufficiourbanistica:
#    driver: bridge