# Generated by Django 4.1.1 on 2022-09-25 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/documents/%Y/%m/%d')),
                ('highlighted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['name'],
            },
        ),
    ]
