# Generated by Django 4.1.1 on 2022-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_fileupload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
