# Generated by Django 4.1.1 on 2022-09-21 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug_category', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug_post', models.SlugField(max_length=70, unique=True)),
                ('header_image', models.ImageField(default='header_default.jpg', upload_to='uploads/images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('contents', tinymce.models.HTMLField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_blogcategory', to='sections.blogcategory')),
            ],
            options={
                'verbose_name': 'Pubblicazione',
                'verbose_name_plural': 'Pubblicazioni',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
