# Generated by Django 4.1.1 on 2022-09-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='Section',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='SectionPost',
        ),
    ]
