# Generated by Django 4.1.1 on 2022-09-22 14:39
from django.db import migrations, models

from ..utils import default_categories, default_posts

class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_categories),
        migrations.RunPython(default_posts),
    ]
