# Generated by Django 4.1.1 on 2022-09-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
