# Generated by Django 4.1.1 on 2022-09-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_rename_blogcategory_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_category', to='sections.section'),
        ),
    ]
