# Generated by Django 4.1.1 on 2022-09-27 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug_category', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='GeoServerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('domain', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Geoserver Domain',
                'verbose_name_plural': 'Geoserver Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='GeoserverWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Geoserver Workspace',
                'verbose_name_plural': 'Geoserver Workspaces',
                'ordering': ['workspace'],
            },
        ),
        migrations.CreateModel(
            name='OGCLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug_post', models.SlugField(max_length=70, unique=True)),
                ('header_image', models.ImageField(default='header_default.jpg', upload_to='uploads/images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('contents', tinymce.models.HTMLField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('map_scaleline', models.BooleanField(default=True)),
                ('map_center_longitude', models.DecimalField(decimal_places=5, default=14.23964, max_digits=10)),
                ('map_center_latitude', models.DecimalField(decimal_places=5, default=40.8429, max_digits=10)),
                ('set_max_zoom', models.IntegerField(default=28)),
                ('set_min_zoom', models.IntegerField(default=0)),
                ('set_zoom_level', models.IntegerField(default=0)),
                ('set_zindex', models.IntegerField(default=1)),
                ('set_opacity', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ogc_layer_name', models.CharField(max_length=100)),
                ('ogc_layer_style', models.CharField(blank=True, max_length=100, null=True)),
                ('ogc_bbox', models.CharField(blank=True, max_length=250, null=True)),
                ('ogc_centroid', models.CharField(blank=True, max_length=250, null=True)),
                ('ogc_legend', models.BooleanField(default=False)),
                ('is_vector', models.BooleanField(default=False)),
                ('is_raster', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='related_ogclayer_categories', to='opengeodata.categories')),
                ('geoserver_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_geoserverdomain', to='opengeodata.geoserverdomain')),
                ('geoserver_workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_geoserverworkspace', to='opengeodata.geoserverworkspace')),
            ],
            options={
                'verbose_name': 'OGC Layer',
                'verbose_name_plural': 'OGC Layers',
                'ordering': ['-publishing_date'],
            },
        ),
        migrations.CreateModel(
            name='WebGISProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('slug_post', models.SlugField(max_length=70, unique=True)),
                ('header_image', models.ImageField(default='header_default.jpg', upload_to='uploads/images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('contents', tinymce.models.HTMLField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('highlighted', models.BooleanField(default=False)),
                ('map_scaleline', models.BooleanField(default=True)),
                ('map_center_longitude', models.DecimalField(decimal_places=5, default=14.23964, max_digits=10)),
                ('map_center_latitude', models.DecimalField(decimal_places=5, default=40.8429, max_digits=10)),
                ('set_max_zoom', models.IntegerField(default=28)),
                ('set_min_zoom', models.IntegerField(default=0)),
                ('set_zoom_level', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='related_webgisproject_categories', to='opengeodata.categories')),
                ('layers', models.ManyToManyField(blank=True, related_name='related_wmslayers', to='opengeodata.ogclayer')),
                ('main_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_main_wmslayer', to='opengeodata.ogclayer')),
            ],
            options={
                'verbose_name': 'WebGIS',
                'verbose_name_plural': 'WebGIS',
                'ordering': ['-publishing_date'],
            },
        ),
    ]
