# Generated by Django 4.1.1 on 2022-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opengeodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogclayer',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='webgisproject',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/%Y/%m/%d'),
        ),
    ]
