# Generated by Django 4.1.1 on 2022-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opengeodata', '0003_categories_remove_ogclayer_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogclayer',
            name='categories',
            field=models.ManyToManyField(related_name='related_ogclayer_categories', to='opengeodata.categories'),
        ),
        migrations.AddField(
            model_name='webgisproject',
            name='categories',
            field=models.ManyToManyField(related_name='related_webgisproject_categories', to='opengeodata.categories'),
        ),
    ]
