# Generated by Django 4.1.1 on 2022-09-27 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(max_length=150)),
                ('url', models.URLField(unique=True)),
                ('column', models.CharField(choices=[('Colonna 1', 1), ('Colonna 2', 2), ('Colonna 3', 3)], max_length=10)),
            ],
            options={
                'verbose_name': 'Link Utile',
                'verbose_name_plural': 'Link Utili',
                'ordering': ['title'],
            },
        ),
    ]
