# Generated by Django 4.1.1 on 2022-09-22 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(max_length=150)),
                ('url', models.URLField()),
                ('column', models.CharField(choices=[(1, 'Colonna 1'), (2, 'Colonna 2'), (3, 'Colonna 3')], max_length=1)),
            ],
            options={
                'verbose_name': 'Link Utile',
                'verbose_name_plural': 'Link Utili',
                'ordering': ['title'],
            },
        ),
    ]
