# Generated by Django 4.1.1 on 2022-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_link_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='column',
            field=models.CharField(choices=[('Colonna 1', 1), (2, 'Colonna 2'), (3, 'Colonna 3')], max_length=10),
        ),
    ]
