# Generated by Django 4.1.1 on 2022-09-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_link_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='column',
            field=models.CharField(choices=[('Colonna 1', 1), ('Colonna 2', 2), ('Colonna 3', 3)], max_length=10),
        ),
    ]
