# Generated by Django 4.1.1 on 2022-09-22 13:40
from django.conf import settings
from django.db import migrations


def create_admin(apps, schema_editor):
    UserProfile = apps.get_model('usermanager', 'UserProfile')

    if settings.ADMIN_USERNAME:
        admin_name = settings.ADMIN_USERNAME
    else:
        admin_name = 'ufficio'

    if settings.ADMIN_PASSWORD:
        admin_password = settings.ADMIN_PASSWORD
    else:
        admin_password = 'urbanistica'

    UserProfile.objects.create_superuser(
        username=admin_name,
        password=admin_password,
    )


# def create_user(apps, schema_editor):
#     UserProfile = apps.get_model('usermanager', 'UserProfile')
#     UserProfile.objects.create_user(
#         username='user',
#         password='opengeodata',
#     )


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
        # migrations.RunPython(create_user),
    ]
