# Generated by Django 4.1.1 on 2022-09-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['username'], 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
